
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action dialogInfoAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.Entry tbTitle;
	private global::Gtk.Entry tbLink;
	private global::Gtk.Entry tbDescription;
	private global::Gtk.Label label3;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Entry tbAuthor;
	private global::Gtk.Label label4;
	private global::Gtk.ComboBox ddCategory;
	private global::Gtk.Label label5;
	private global::Gtk.Entry tbCategory;
	private global::Gtk.VSeparator vseparator1;
	private global::Gtk.Button btPublish;
	private global::Gtk.Button btDelete;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", null, null, "gtk-dialog-info");
		w1.Add (this.dialogInfoAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", null, null, "gtk-quit");
		w1.Add (this.quitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("RSS Editor");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./rss.ico"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='dialogInfoAction' action='dialogInfoAction'/><toolitem name='quitAction' action='quitAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.fixed1.Add (this.toolbar1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.toolbar1]));
		w2.X = 2;
		w2.Y = 4;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tbTitle = new global::Gtk.Entry ();
		this.tbTitle.WidthRequest = 450;
		this.tbTitle.CanFocus = true;
		this.tbTitle.Name = "tbTitle";
		this.tbTitle.IsEditable = true;
		this.tbTitle.InvisibleChar = '•';
		this.fixed1.Add (this.tbTitle);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbTitle]));
		w3.X = 110;
		w3.Y = 65;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tbLink = new global::Gtk.Entry ();
		this.tbLink.WidthRequest = 450;
		this.tbLink.CanFocus = true;
		this.tbLink.Name = "tbLink";
		this.tbLink.IsEditable = true;
		this.tbLink.InvisibleChar = '•';
		this.fixed1.Add (this.tbLink);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbLink]));
		w4.X = 110;
		w4.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tbDescription = new global::Gtk.Entry ();
		this.tbDescription.WidthRequest = 450;
		this.tbDescription.CanFocus = true;
		this.tbDescription.Name = "tbDescription";
		this.tbDescription.IsEditable = true;
		this.tbDescription.InvisibleChar = '•';
		this.fixed1.Add (this.tbDescription);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbDescription]));
		w5.X = 110;
		w5.Y = 156;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w6.X = 22;
		w6.Y = 159;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w7.X = 70;
		w7.Y = 69;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Link");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w8.X = 72;
		w8.Y = 115;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tbAuthor = new global::Gtk.Entry ();
		this.tbAuthor.WidthRequest = 450;
		this.tbAuthor.CanFocus = true;
		this.tbAuthor.Name = "tbAuthor";
		this.tbAuthor.IsEditable = true;
		this.tbAuthor.InvisibleChar = '•';
		this.fixed1.Add (this.tbAuthor);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbAuthor]));
		w9.X = 110;
		w9.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Author");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w10.X = 54;
		w10.Y = 207;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.ddCategory = global::Gtk.ComboBox.NewText ();
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Notícias"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Novidades"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Artigos"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Publicações"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Eventos"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Entrevistas"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Reviews"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Lançamentos"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Imagens"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Música"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Vídeos"));
		this.ddCategory.AppendText (global::Mono.Unix.Catalog.GetString ("Sites"));
		this.ddCategory.WidthRequest = 149;
		this.ddCategory.Name = "ddCategory";
		this.fixed1.Add (this.ddCategory);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ddCategory]));
		w11.X = 110;
		w11.Y = 249;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Category");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w12.X = 40;
		w12.Y = 256;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tbCategory = new global::Gtk.Entry ();
		this.tbCategory.WidthRequest = 293;
		this.tbCategory.CanFocus = true;
		this.tbCategory.Name = "tbCategory";
		this.tbCategory.IsEditable = true;
		this.tbCategory.InvisibleChar = '•';
		this.fixed1.Add (this.tbCategory);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbCategory]));
		w13.X = 267;
		w13.Y = 251;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.HeightRequest = 27;
		this.vseparator1.Name = "vseparator1";
		this.fixed1.Add (this.vseparator1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.vseparator1]));
		w14.X = 262;
		w14.Y = 301;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btPublish = new global::Gtk.Button ();
		this.btPublish.WidthRequest = 145;
		this.btPublish.CanFocus = true;
		this.btPublish.Name = "btPublish";
		this.btPublish.UseUnderline = true;
		this.btPublish.Label = global::Mono.Unix.Catalog.GetString ("Publish!");
		this.fixed1.Add (this.btPublish);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btPublish]));
		w15.X = 109;
		w15.Y = 300;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btDelete = new global::Gtk.Button ();
		this.btDelete.WidthRequest = 290;
		this.btDelete.CanFocus = true;
		this.btDelete.Name = "btDelete";
		this.btDelete.UseUnderline = true;
		this.btDelete.Label = global::Mono.Unix.Catalog.GetString ("Delete last publication");
		this.fixed1.Add (this.btDelete);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btDelete]));
		w16.X = 270;
		w16.Y = 300;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 619;
		this.DefaultHeight = 361;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.Create_clicked);
		this.openAction.Activated += new global::System.EventHandler (this.Options_clicked);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.About_clicked);
		this.quitAction.Activated += new global::System.EventHandler (this.Quit_clicked);
		this.btPublish.Clicked += new global::System.EventHandler (this.btPublish_Clicked);
		this.btDelete.Clicked += new global::System.EventHandler (this.btDelete_Clicked);
	}
}
