
// This file has been generated by the GUI designer. Do not modify.
namespace rss_editor
{
	public partial class Create
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Entry tbTitle;
		private global::Gtk.Entry tbLink;
		private global::Gtk.Entry tbDescription;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Entry tbCopyright;
		private global::Gtk.Label label5;
		private global::Gtk.Entry tbImgURL;
		private global::Gtk.Entry tbImgTitle;
		private global::Gtk.Label label8;
		private global::Gtk.Label label7;
		private global::Gtk.Label label9;
		private global::Gtk.Entry tbImgLink;
		private global::Gtk.Label label6;
		private global::Gtk.DrawingArea drawingarea1;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Button btSave;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget rss_editor.Create
			this.Name = "rss_editor.Create";
			this.Title = global::Mono.Unix.Catalog.GetString ("Create RSS");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child rss_editor.Create.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbTitle = new global::Gtk.Entry ();
			this.tbTitle.WidthRequest = 409;
			this.tbTitle.CanFocus = true;
			this.tbTitle.Name = "tbTitle";
			this.tbTitle.IsEditable = true;
			this.tbTitle.InvisibleChar = '•';
			this.fixed1.Add (this.tbTitle);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbTitle]));
			w1.X = 121;
			w1.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbLink = new global::Gtk.Entry ();
			this.tbLink.WidthRequest = 409;
			this.tbLink.CanFocus = true;
			this.tbLink.Name = "tbLink";
			this.tbLink.IsEditable = true;
			this.tbLink.InvisibleChar = '•';
			this.fixed1.Add (this.tbLink);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbLink]));
			w2.X = 121;
			w2.Y = 77;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbDescription = new global::Gtk.Entry ();
			this.tbDescription.WidthRequest = 409;
			this.tbDescription.CanFocus = true;
			this.tbDescription.Name = "tbDescription";
			this.tbDescription.IsEditable = true;
			this.tbDescription.InvisibleChar = '•';
			this.fixed1.Add (this.tbDescription);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbDescription]));
			w3.X = 121;
			w3.Y = 123;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 86;
			w4.Y = 36;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Link");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w5.X = 88;
			w5.Y = 81;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w6.X = 37;
			w6.Y = 128;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbCopyright = new global::Gtk.Entry ();
			this.tbCopyright.WidthRequest = 409;
			this.tbCopyright.CanFocus = true;
			this.tbCopyright.Name = "tbCopyright";
			this.tbCopyright.IsEditable = true;
			this.tbCopyright.InvisibleChar = '•';
			this.fixed1.Add (this.tbCopyright);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbCopyright]));
			w7.X = 121;
			w7.Y = 170;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Copyright");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w8.X = 49;
			w8.Y = 175;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbImgURL = new global::Gtk.Entry ();
			this.tbImgURL.WidthRequest = 363;
			this.tbImgURL.CanFocus = true;
			this.tbImgURL.Name = "tbImgURL";
			this.tbImgURL.IsEditable = true;
			this.tbImgURL.InvisibleChar = '•';
			this.fixed1.Add (this.tbImgURL);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbImgURL]));
			w9.X = 167;
			w9.Y = 219;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbImgTitle = new global::Gtk.Entry ();
			this.tbImgTitle.WidthRequest = 363;
			this.tbImgTitle.CanFocus = true;
			this.tbImgTitle.Name = "tbImgTitle";
			this.tbImgTitle.IsEditable = true;
			this.tbImgTitle.InvisibleChar = '•';
			this.fixed1.Add (this.tbImgTitle);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbImgTitle]));
			w10.X = 167;
			w10.Y = 266;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w11.X = 130;
			w11.Y = 270;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("URL");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w12.X = 134;
			w12.Y = 225;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Link");
			this.fixed1.Add (this.label9);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
			w13.X = 134;
			w13.Y = 320;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tbImgLink = new global::Gtk.Entry ();
			this.tbImgLink.WidthRequest = 363;
			this.tbImgLink.CanFocus = true;
			this.tbImgLink.Name = "tbImgLink";
			this.tbImgLink.IsEditable = true;
			this.tbImgLink.InvisibleChar = '•';
			this.fixed1.Add (this.tbImgLink);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tbImgLink]));
			w14.X = 167;
			w14.Y = 314;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Imagem");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w15.X = 50;
			w15.Y = 269;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.fixed1.Add (this.drawingarea1);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.drawingarea1]));
			w16.X = 104;
			w16.Y = 282;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.HeightRequest = 108;
			this.vseparator1.Name = "vseparator1";
			this.fixed1.Add (this.vseparator1);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.vseparator1]));
			w17.X = 115;
			w17.Y = 228;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btSave = new global::Gtk.Button ();
			this.btSave.CanFocus = true;
			this.btSave.Name = "btSave";
			this.btSave.UseUnderline = true;
			this.btSave.Label = global::Mono.Unix.Catalog.GetString ("Save RSS File");
			this.fixed1.Add (this.btSave);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btSave]));
			w18.X = 113;
			w18.Y = 363;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 591;
			this.DefaultHeight = 421;
			this.Show ();
			this.btSave.Clicked += new global::System.EventHandler (this.btSave_Clicked);
		}
	}
}
